Repository WildCodeSchool/toulouse-0918-java-cafeconcert, pull requests merged in 2018-10, with the labels that each got.

#4 Creation of BarAdapter, BarList and the item, added variable for pict…
  app/src/main/java/fr/wildcodeschool/cafeconcert/Bar.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/activity_bar_list.xml
  app/src/main/res/layout/item_bar.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#5 Add GPS location and clean MapsActivity code
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/values/strings.xml
Labels: Conflicts solved, Relu

#8 Fixing bugs
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
Labels: Conflicts solved, Relu

#13 Problems fixed
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
Labels: Relu

#11 Login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/InscriptionActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/drawable-hdpi/backgroundlog.png
  app/src/main/res/drawable-hdpi/backgroundlogin.png
  app/src/main/res/drawable-hdpi/blueee.png
  app/src/main/res/drawable-hdpi/ic_action_pass.png
  app/src/main/res/drawable-hdpi/ic_action_person.png
  app/src/main/res/drawable-hdpi/ic_action_user.png
  app/src/main/res/drawable-mdpi/backgroundlog.png
  app/src/main/res/drawable-mdpi/backgroundlogin.png
  app/src/main/res/drawable-mdpi/blueee.png
  app/src/main/res/drawable-mdpi/ic_action_pass.png
  app/src/main/res/drawable-mdpi/ic_action_person.png
  app/src/main/res/drawable-mdpi/ic_action_user.png
  app/src/main/res/drawable-xhdpi/backgroundlog.png
  app/src/main/res/drawable-xhdpi/backgroundlogin.png
  app/src/main/res/drawable-xhdpi/blueee.png
  app/src/main/res/drawable-xhdpi/ic_action_pass.png
  app/src/main/res/drawable-xhdpi/ic_action_person.png
  app/src/main/res/drawable-xhdpi/ic_action_user.png
  app/src/main/res/drawable-xxhdpi/backgroundlog.png
  app/src/main/res/drawable-xxhdpi/backgroundlogin.png
  app/src/main/res/drawable-xxhdpi/blueee.png
  app/src/main/res/drawable-xxhdpi/ic_action_pass.png
  app/src/main/res/drawable-xxhdpi/ic_action_person.png
  app/src/main/res/drawable-xxhdpi/ic_action_user.png
  app/src/main/res/drawable-xxxhdpi/backgroundlog.png
  app/src/main/res/drawable-xxxhdpi/backgroundlogin.png
  app/src/main/res/drawable-xxxhdpi/blueee.png
  app/src/main/res/drawable/oval.xml
  app/src/main/res/font/aref_ruqaa.xml
  app/src/main/res/layout/activity_inscription.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Relu

#12 Pop up bar
  .idea/assetWizardSettings.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/custom_info_adapter.xml
  app/src/main/res/mipmap-xxxhdpi/brokenheart_empty.png
  app/src/main/res/mipmap-xxxhdpi/fonddecran.jpg
  app/src/main/res/mipmap-xxxhdpi/globeicon.png
  app/src/main/res/mipmap-xxxhdpi/heartempty.png
  app/src/main/res/mipmap-xxxhdpi/navigate.png
  app/src/main/res/mipmap-xxxhdpi/phonelogo.png
Labels: Relu

#17 popup constraint fixed
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/custom_info_adapter.xml
Labels: Relu

#18 Adding setting user preferences
  .idea/assetWizardSettings.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/Bar.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/drawable-hdpi/neutral_dislike_icon.png
  app/src/main/res/drawable-hdpi/neutral_like_icon.png
  app/src/main/res/drawable-mdpi/neutral_dislike_icon.png
  app/src/main/res/drawable-mdpi/neutral_like_icon.png
  app/src/main/res/drawable-xhdpi/neutral_dislike_icon.png
  app/src/main/res/drawable-xhdpi/neutral_like_icon.png
  app/src/main/res/drawable-xxhdpi/neutral_dislike_icon.png
  app/src/main/res/drawable-xxhdpi/neutral_like_icon.png
  app/src/main/res/drawable-xxxhdpi/neutral_dislike_icon.png
  app/src/main/res/drawable-xxxhdpi/neutral_like_icon.png
Labels: Relu

#20 Création layout du profil
  .idea/assetWizardSettings.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/Profile.java
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#21 Navigation
  .idea/assetWizardSettings.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
Labels: Relu

#22 Navigation on list page
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/item_bar.xml
Labels: Relu

#23 Like filter
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/activity_bar_list.xml
  app/src/main/res/layout/switch_item.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/values/strings.xml
Labels: Conflicts solved, Relu

#26 Login activity
  app/build.gradle
  app/google-services.json
  app/src/debug/res/values/google_maps_api.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/InscriptionActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/res/layout/activity_inscription.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#27 Listlike
  .idea/assetWizardSettings.xml
  app/build.gradle
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/Profile.java
  app/src/main/res/drawable/photodecafe.jpg
  app/src/main/res/layout/activity_bar_list.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/item_bar.xml
Labels: Relu

#28 Camera
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/Profile.java
  app/src/main/res/xml/file_paths.xml
Labels: Relu

#30 Optimization
  app/src/debug/res/values/google_maps_api.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/Profile.java
  app/src/main/res/layout/custom_info_adapter.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#31 Likes in list
  .idea/assetWizardSettings.xml
  app/build.gradle
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/item_bar.xml
Labels: Relu

#34 Fixing firebase connexion
  app/src/main/java/fr/wildcodeschool/cafeconcert/Bar.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
Labels: Relu

#33 Suppression crash au click d'un site web vide
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/values/strings.xml
Labels: Relu

#35 Suppression share menu
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/Profile.java
  app/src/main/res/menu/drawer_menu.xml
Labels: Relu

#38 Langage uniformisation
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#41 Filter by distance
  app/src/main/java/fr/wildcodeschool/cafeconcert/Bar.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/switch_item_by_distance.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#40 Auth function
  app/src/main/java/fr/wildcodeschool/cafeconcert/Bar.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/InscriptionActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/drawable-xxhdpi/fond_txt.xml
  app/src/main/res/drawable/ic_my_location_black_24dp.xml
  app/src/main/res/layout/item_bar.xml
  app/src/main/res/menu/drawer_menu.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#45 Button to map
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarListActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/InscriptionActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/res/layout/item_bar.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#46 Profile layout
  .idea/assetWizardSettings.xml
  app/src/main/java/fr/wildcodeschool/cafeconcert/Bar.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/BarAdapter.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/InscriptionActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/cafeconcert/Profile.java
  app/src/main/res/drawable-xxhdpi/fond_txt.xml
  app/src/main/res/drawable/ic_camera_alt_black_24dp.xml
  app/src/main/res/drawable/ic_image_black_24dp.xml
  app/src/main/res/layout/activity_inscription.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/item_bar.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#63 Résolution du 'chargement infini' lors du retour sur le mode invité
  app/src/main/java/fr/wildcodeschool/cafeconcert/MainActivity.java
Labels: bug
